from pathlib import Path

path = Path("local/crates/fennara-daemon/src/runtime_daemon/chat/generation/publisher.rs")
text = path.read_text(encoding="utf-8")
marker = """                    StreamItem::FunctionCallError { id, name, arguments, message } => {\n"""
block = """                    StreamItem::ExternalTool {\n                        id,\n                        name,\n                        arguments,\n                        content,\n                        status,\n                    } => {\n                        let terminal = external_tool_status_is_terminal(&status);\n                        trace.with_tool_call(id.clone()).event_status(\n                            \"provider.external_tool.updated\",\n                            &status,\n                            json!({\n                                \"tool_name\": name.as_str(),\n                                \"arguments_bytes\": arguments.len(),\n                                \"content_bytes\": content.len(),\n                                \"terminal\": terminal\n                            }),\n                        );\n                        send_json(\n                            sender,\n                            json!({\n                                \"type\": \"chat_item_update\",\n                                \"request_id\": request_id.clone(),\n                                \"item\": {\n                                    \"id\": id,\n                                    \"type\": if terminal { \"tool_result\" } else { \"function_call\" },\n                                    \"name\": name,\n                                    \"arguments\": arguments,\n                                    \"content\": content,\n                                    \"status\": status\n                                }\n                            }),\n                        )\n                        .await?;\n                    }\n"""
if "StreamItem::ExternalTool" not in text:
    if text.count(marker) != 1:
        raise RuntimeError("publisher FunctionCallError marker mismatch")
    path.write_text(text.replace(marker, block + marker, 1), encoding="utf-8", newline="\n")
